[package]
name = "nim"
version = "0.1.0"
authors = ["Colin <colin@mooooo.ooo>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
